_home_route:
    pattern:  /
    defaults: { _controller: AcmeStoreBundle:Default:home }

_create_route:
    pattern: /create
    defaults: { _controller: AcmeStoreBundle:Default:create }

_show_route:
    pattern: /show/{id}
    defaults: { _controller: AcmeStoreBundle:Default:show, id: 1 }

_show_description_route:
    pattern: /showdescription/{id}
    defaults: { _controller: AcmeStoreBundle:Default:showDescription, id: 1 }

_update_route:
    pattern: /update/{id}
    defaults: { _controller: AcmeStoreBundle:Default:update }

_remove_route:
    pattern: /remove/{id}
    defaults: { _controller: AcmeStoreBundle:Default:remove }